import { redirect } from "next/navigation";
import ArrowBackIosRoundedIcon from "@mui/icons-material/ArrowBackIosRounded";
import ReduxProvider from "@/redux/redux-provider";
import { createClient } from "@/utils/supabase/server";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const goToLanding = async () => {
    "use server";
    return redirect("/");
  };

  

  return (
    <html lang="en">
      <ReduxProvider>
        <body className="relative bg-secondaryColor">
          <nav className="absolute left-10 top-10 z-50 text-white">
            <form action={goToLanding}>
              <button>
                <ArrowBackIosRoundedIcon fontSize="small" />
              </button>
            </form>
          </nav>
          <main>{children}</main>
        </body>
      </ReduxProvider>
    </html>
  );
}
