import { redirect } from 'next/navigation';
import ArrowBackIosRoundedIcon from '@mui/icons-material/ArrowBackIosRounded';
import ReduxProvider from '@/redux/redux-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const goToLanding = async () => {
    'use server';
    return redirect('/');
  };

  return (
    <html lang="en">
      <ReduxProvider>
        <body className="bg-secondaryColor relative">
          <nav className="absolute text-white z-50 top-10 left-10">
            <form action={goToLanding}>
              <button>
                <ArrowBackIosRoundedIcon fontSize="small" />
              </button>
            </form>
          </nav>
          <main>{children}</main>
        </body>
      </ReduxProvider>
    </html>
  );
}
