import ReduxProvider from "@/redux/redux-provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
      <body>{children}</body>
      </ReduxProvider>
    </html>
  )
}
